name:                definitely-not-fire-emblem
version:             0.1.0.0
github:              "oinkiguana/definitely-not-fire-emblem"
license:             BSD3
author:              "Cameron Eldridge"
maintainer:          "cameldridge+git@gmail.com"
copyright:           "2018 Cameron Eldridge"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/oinkiguana/definitely-not-fire-emblem#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- colour
- sdl2
- sdl2-image
- sdl2-ttf
- symbol
- mtl

library:
  source-dirs: src

executables:
  dnfe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - definitely-not-fire-emblem

tests:
  dnfe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - definitely-not-fire-emblem
